SourceWrestlingSchool/Models/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Faker;

namespace SourceWrestlingSchool.Models
{
    /// <summary>Represents a record of an outstanding payment in the system.</summary>
    public class Payment
    {
        /// <summary>Gets or sets the id record of the payment name of the instructor teaching the lesson.</summary>
        public int PaymentId { get; set; }
        /// <summary>Gets or sets the date the payment was added to the system.</summary>
        [DataType(DataType.Date)]
        [Display(Name ="Date Added")]
        public DateTime PaymentDate { get; set; }
        /// <summary>Gets or sets the payment amount.</summary>
        [DataType(DataType.Currency)]
        [Display(Name = "Amount")] 
        public decimal PaymentAmount { get; set; }
        /// <summary>Gets or sets a description of what the payment is for.</summary>
        [Display(Name = "Description")]
        public string PaymentDescription { get; set; }
        /// <summary>Gets or sets a value indiccated whether the payement was completed or not.</summary>
        [Display(Name = "Settled?")]
        public bool PaymentSettled { get; set; }
        /// <summary>Gets or sets the Braintree transaction ID of the payment if it was settled.</summary>
        public string TransactionId  { get; set; }
        /// <summary>Gets or sets a list of seats that is attached to a live event booking payment.</summary>
        public virtual ICollection<Seat> Seats  { get; set; }

        //navigational Properties
        /// <summary>Gets or sets the id of the user that has been charged with the payment.</summary>
        public string UserId { get; set; }
        /// <summary>Gets or sets the user that has been charged with the payment.</summary>
        public ApplicationUser User { get; set; }
    }
}

SourceWrestlingSchool/Controllers/PaymentsController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.UI;
using SourceWrestlingSchool.Models;
using Braintree;

namespace SourceWrestlingSchool.Controllers
{
    /// <summary>
    ///     Controller to handle historical and outstanding payments
    /// </summary>
    public class PaymentsController : Controller
    {
        /// <summary>
        ///     Virtual representation of the database
        /// </summary>
        private readonly ApplicationDbContext _db = new ApplicationDbContext();

        /// <summary>
        ///     Get all payments listed in the database.
        ///     Attach the user who made the payment to each entity.
        ///     Send the list as a ViewModel to populate the Index View.
        /// </summary>
        /// <returns>The index view, along with the list of attached payments</returns>
        // GET: Payments
        public ActionResult Index()
        {
            var payments = _db.Payments.Include(p => p.User);
            return View(payments.ToList());
        }

        /// <summary>
        ///     Show the details of a particular payment.
        /// </summary>
        /// <remarks>
        ///     If no id is sent, display a bad request error page.
        ///     Else
        ///         Get the payement from the database with a matching id.
        ///         Attach the user associated with the payment entity.
        ///         Send the payment as the model to populate the Detail view.
        /// </remarks>
        /// <param name="id">The id of the payment entity</param>
        /// <returns>The Payment Detail View, with a Payment model parameter</returns>
        // GET: Payments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payment payment = _db.Payments.Where(p => p.PaymentId == id).Include(u => u.User).Single();
            payment.UserId = payment.User.Id;
            
            return View(payment);
        }

        /// <summary>
        ///     Display all outstanding payments of the current user 
        /// </summary>
        /// <remarks>
        ///     Retrieve all non-settled payments from the database, that have the user's email address attached to them.
        ///     If the page request came from the payment gateway, load the notification message sent into a TempData object.
        ///     Load the Outstaning Payment list, with the payment list as a sent model to populate it.
        /// </remarks>
        /// <returns>The Ouststanding Payment view, with the filtered user's own payments as the send model. </returns>
        public ActionResult Outstanding()
        { 
            using (_db)
            {
                //var user = _db.Users.Single(u => u.Email == User.Identity.Name);
                //var model = _db.Payments
                //            .Where(p => p.UserId == user.Id && p.PaymentSettled == false)
                //            .Include(p => p.User)
                //            .ToList();
                var email = User.Identity.Name;
                var model = _db.Payments
                            .Where(p => p.User.Email == email && p.PaymentSettled == false)
                            .Include(p => p.User)
                            .ToList();
                ViewBag.Message = TempData["message"];
                return View(model);
            }
        }

        /// <summary>
        ///     Load a payment gateway to settle an outstanding payment. 
        /// </summary>
        /// <remarks>
        ///     Retrieve the payment details with a matching paymentID as the passed parameter.
        ///     Search the Braintree payment gateway to check if the user is an existing customer in the Vault.
        ///     If a match is found
        ///         Generate a client token using the customer's vault ID.s
        ///     If no match exists
        ///         Use the gateway to generate a token for the checkout session.
        ///     In either case, store the clientToken in a ViewBag for clientside use. 
        /// </remarks>
        /// <param name="paymentId">The id of the payment to be processed</param>
        /// <returns> The SendPayment view, sending the Payment entity as the viewmodel</returns>
        [HttpGet]
        public ActionResult SendPayment(int? paymentId)
        {
            if (paymentId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payment payment = _db.Payments
                              .Where(p => p.PaymentId == paymentId)
                              .Include(u =>u.User)
                              .Single();
            if (payment == null)
            {
                return HttpNotFound();
            }

            //Generate payment token
            var customerRequest = new CustomerSearchRequest().Email.Is(User.Identity.Name);
            ResourceCollection<Customer> collection = PaymentGateways.Gateway.Customer.Search(customerRequest);
            string clientToken;
            if (collection.Ids.Count != 0)
            {
                string custId = collection.FirstItem.Id;
                clientToken = PaymentGateways.Gateway.ClientToken.generate(
                    new ClientTokenRequest
                    {
                        CustomerId = custId
                    }
                );
            }
            else
            {
                clientToken = PaymentGateways.Gateway.ClientToken.generate();
            }
            ViewBag.ClientToken = clientToken;
            ViewBag.Message = TempData["message"];

            return View(payment);
        }

        /// <summary>
        ///     Process an attempt at payment.
        /// </summary>
        /// <remarks>
        ///     Collect the paymentID, payment nonce, and transaction amount from the client checkout form.
        ///     Create a new Transaction request using the retrieved data
        ///     Submit the transaction for settlement and receive a result object from the gateway.
        ///     If the payment is successful
        ///         Retrive the payment details from the database
        ///         Set the payment status to settled
        ///         Create a postive notification
        ///         Save the change to the database
        ///         Load the outstanding payment list
        ///     Else
        ///         Use the list of errors in the result to create a negative notification
        ///         Refresh the page to highlght the payment failure
        /// </remarks>
        /// <param name="collection">The collection of data from the checkout form</param>
        /// <returns>
        ///     The Outstanding Payment list if the payment was successful.
        ///     Refresh for the current page if the payment failed.
        /// </returns>
        [HttpPost]
        public ActionResult SendPayment(FormCollection collection)
        {
             using (_db)
            {
                string nonceFromTheClient = collection["payment_method_nonce"];
                decimal amount = decimal.Parse(collection["amount"]);
                int pId = int.Parse(collection["payID"]);

                var request = new TransactionRequest
                {
                    Amount = amount,
                    PaymentMethodNonce = nonceFromTheClient,
                    CustomFields = new Dictionary<string, string>
                {
                    { "description",  collection["description"]},
                },
                    Options = new TransactionOptionsRequest
                    {
                        SubmitForSettlement = true
                    }
                };

                Result<Transaction> result = PaymentGateways.Gateway.Transaction.Sale(request);

                if (result.IsSuccess())
                {
                    Payment payment = _db.Payments
                                      .Where(p => p.PaymentId == pId && p.PaymentSettled == false)
                                      .Include(p => p.User)
                                      .Single();

                    payment.PaymentSettled = true;
                    payment.TransactionId = result.Target.Id;
                    
                    TempData["message"] = "Payment Successful.";
                    _db.SaveChanges();
                    return RedirectToAction("Outstanding");
                }
                
                TempData["message"] = "";
                foreach (var error in result.Errors.All())
                {
                    TempData["message"] = TempData["message"] + error.Message + " ";
                }
                _db.SaveChanges();

                return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
            }
        }

        /// <summary>
        ///     Display a user's purchase history.
        /// </summary>
        /// <remarks>
        ///     Retrieve all payments from the database that have the user's email attached to them.
        ///     Remove any payments that have been previously refunded.
        ///     Load the PaymentHistory view.
        /// </remarks>
        /// <returns>A view displayng all previous settled purchases.</returns>
        public ActionResult PaymentHistory()
        {
            var model = _db.Payments
                        .Where(p => p.User.Email == User.Identity.Name && p.PaymentSettled)
                        .ToList();
            var user = _db.Users.Single(u => u.Email == User.Identity.Name);
            ViewBag.Username = user.FirstName + " " + user.LastName;
            foreach (Payment payment in model)
            {

SourceWrestlingSchool/Views/Payments/Create.cshtml
@model SourceWrestlingSchool.Models.Payment

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Payment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.PaymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SourceWrestlingSchool/Views/Payments/Delete.cshtml
@model SourceWrestlingSchool.Models.Payment

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Payment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SourceWrestlingSchool/Views/Payments/Details.cshtml
@model SourceWrestlingSchool.Models.Payment

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Payment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentDescription)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

SourceWrestlingSchool/Views/Payments/Edit.cshtml
@model SourceWrestlingSchool.Models.Payment

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Payment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PaymentId)

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SourceWrestlingSchool/Views/Payments/Index.cshtml
@model IEnumerable<SourceWrestlingSchool.Models.Payment>

@{
    ViewBag.Title = "Payment Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Menu {
    @Scripts.Render("~/Scripts/Tables/Data/menu")
}

@Styles.Render("~/AdminLTE/plugins/datatables/css")
<style>
    .label{ -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
          }
</style>

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Site Payment History</h3>
            </div>
            <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.User.FirstName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PaymentDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PaymentAmount)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PaymentDescription)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PaymentSettled)
                        </th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model) {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.User.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PaymentDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PaymentAmount)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PaymentDescription)
                            </td>
                            <td>
                                @if (item.PaymentSettled)
                                {
                                    <small class="label label-success">Settled</small>
                                }
                                else
                                {
                                    <small class="label label-danger">Outstanding</small>
                                }
                            </td>
                            <td>
                                @Html.ActionLink("Details", "Details", new { id=item.PaymentId }) |
                            </td>
                        </tr>
                    }
                    </tbody>
                    <tfoot>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.User.FirstName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PaymentDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PaymentAmount)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PaymentDescription)
                        </th>
                        <th></th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <a class="btn btn-app" href='@Url.Action("ExportOutstandingToExcel", "Payments")'>
        <i class="fa fa-file-excel-o"></i> Export To Excel
    </a>
    <a class="btn btn-app" href='@Url.Action("ExportOutstandingToPdf", "Payments")'>
        <i class="fa fa-file-pdf-o"></i> Export To PDF
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/AdminLTE/plugins/datatables/js")
    @Scripts.Render("~/Scripts/Tables/Data")
}

SourceWrestlingSchool/Views/Payments/Outstanding.cshtml
@model IEnumerable<SourceWrestlingSchool.Models.Payment>

@{
    ViewBag.Title = "Outstanding";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Outstanding Payments</h2>

@section Menu {
    @Scripts.Render("~/Scripts/Tables/Data/menu")
}

@Styles.Render("~/AdminLTE/plugins/datatables/css")

@if (ViewBag.Message != null)
{
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-thumbs-up"></i> Thank You!</h4>
        @Html.Raw(ViewBag.Message)
    </div>
}

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Outstanding Payments</h3>
            </div>
            <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.PaymentDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PaymentAmount)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PaymentDescription)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PaymentDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PaymentAmount)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PaymentDescription)
                                </td>
                                <td>
                                    @using (Html.BeginForm("SendPayment", "Payments", FormMethod.Get))
                                    {
                                        <input type="hidden" name="paymentID" value=@item.PaymentId />
                                        <input class="btn btn-success" type="submit" value="Send Payment" />
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.PaymentDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PaymentAmount)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PaymentDescription)
                            </th>
                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/AdminLTE/plugins/datatables/js")
    @Scripts.Render("~/Scripts/Tables/Data")
}

SourceWrestlingSchool/Views/Payments/PaymentHistory.cshtml
@model IEnumerable<SourceWrestlingSchool.Models.Payment>

@{
    ViewBag.Title = "Payment History";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Menu {
    @Scripts.Render("~/Scripts/Tables/Data/menu")
}

@Styles.Render("~/AdminLTE/plugins/datatables/css")
<style>
    .label {
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
    }
</style>

@if (ViewBag.Message != null)
{
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
        Your attempted refund failed for the following reasons : @Html.Raw(ViewBag.Message)
    </div>
}

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">@ViewBag.Username - Payment History</h3>
            </div>
            <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.PaymentDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PaymentAmount)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PaymentDescription)
                        </th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model) {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.PaymentDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PaymentAmount)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PaymentDescription)
                            </td>
                            <td>
                                @Html.ActionLink("Refund", "Refund", new { id=item.TransactionId })
                            </td>
                        </tr>
                    }
                    </tbody>
                    <tfoot>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.PaymentDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PaymentAmount)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PaymentDescription)
                        </th>
                        <th></th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <a class="btn btn-app" href='@Url.Action("ExportOutstandingToExcel", "Payments")'>
        <i class="fa fa-file-excel-o"></i> Export To Excel
    </a>
    <a class="btn btn-app" href='@Url.Action("ExportOutstandingToPdf", "Payments")'>
        <i class="fa fa-file-pdf-o"></i> Export To PDF
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/AdminLTE/plugins/datatables/js")
    @Scripts.Render("~/Scripts/Tables/Data")
}

SourceWrestlingSchool/Views/Payments/RefundSuccess.cshtml
@model string
@{
    ViewBag.Title = "RefundSuccess";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model != null)
{
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-check"></i> Alert!</h4>
        @Model
    </div>
}
<br />
@Html.ActionLink("Back To Payment History","PaymentHistory");