SourceWrestlingSchool/Models/SubscriptionViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SourceWrestlingSchool.Models
{
    /// <summary>Represents the data model of a student's subscription agreement.</summary>
    public class SubscriptionViewModel
    {
        /// <summary>Gets or sets the id record of the seat in the database.</summary>
        [Key]
        public int SubId { get; set; }
        /// <summary>Gets or sets a value indicating whether.</summary>
        public bool IsSubscribed { get; set; }
        /// <summary>Gets or sets the id of the subscription agreement.</summary>
        public string SubscriptionId { get; set; }
        /// <summary>Gets or sets the last payment date of the subscription.</summary>
        public DateTime? LastPaymentDate { get; set; }
        /// <summary>Gets or sets the next payment date for the subscription.</summary>
        public DateTime? NextDueDate { get; set; }
        /// <summary>Gets or sets the name of the user attached to the subscription.</summary>
        public string Username { get; set; }
    }
}

SourceWrestlingSchool/Controllers/SubscriptionController.cs
using Braintree;
using SourceWrestlingSchool.Models;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;

namespace SourceWrestlingSchool.Controllers
{
    /// <summary>
    ///     Controller to handles all actions regarding student monthly subscriptions
    /// </summary>
    public class SubscriptionController : Controller
    {
        /// <summary>
        ///     Virtual representation of the database.
        /// </summary>
        private readonly ApplicationDbContext _db = new ApplicationDbContext();

        /// <summary>
        ///     Display a student user's subscription information, or offer a number of membership plans
        /// </summary>
        /// <remarks>
        ///     Create a new Subscription model
        ///     Get the current user's details from the database
        ///     Check to see if the user has a subscription.
        ///     If the user is subscribed,
        ///          Checks the financial gateway for the matching customer record as the user.
        ///          When the match is found, add the relevant subscription information to the data model.
        ///     Send the model along with the View
        /// </remarks>
        /// <returns>
        ///     The details of the student's subscription if the student has a membership.
        ///     The list of membership plans available if not subscribed.
        /// </returns>
        // GET: Subscription
        public ActionResult Index()
        {
            SubscriptionViewModel model = new SubscriptionViewModel();
            
            using (_db)
            {
                ApplicationUser user = _db.Users.First(u => u.UserName.Equals(User.Identity.Name));

                //Ternary operator to evaluate if a user has a subscription
                model.IsSubscribed = (user.MemberLevel != null);
                if (model.IsSubscribed)
                {
                    model.Username = user.FirstName + " " + user.LastName;
                    var request = new CustomerSearchRequest().Email.Is(User.Identity.Name);
                    ResourceCollection<Customer> collection = PaymentGateways.Gateway.Customer.Search(request);
                    if (collection.Ids.Count != 0)
                    {
                        foreach (var entry in collection.FirstItem.CreditCards)
                        {
                            foreach (var sub in entry.Subscriptions)
                            {
                                if (sub.Status == SubscriptionStatus.ACTIVE)
                                {
                                    model.LastPaymentDate = sub.PaidThroughDate.Value.Date;
                                    model.NextDueDate = sub.NextBillingDate.Value.Date;
                                    model.SubscriptionId = sub.Id;
                                }
                            }
                        }
                    }
                }
            }
            return View(model);
        }

        /// <summary>
        ///     Load the view to set up a new subscription agreement.
        /// </summary>
        /// <remarks>
        ///     Instantiate a new ViewModel, using the id parameter of the subscription plan to be started.
        ///     Get the current user's details from the database.
        ///     Search the Braintree payment gateway to check if the user is an existing customer in the Vault.
        ///     If a match is found
        ///         Generate a client token using the customer's vault ID.s
        ///     If no match exists
        ///         Use the gateway to generate a token for the checkout session.
        ///     In either case, store the clientToken in a ViewBag for clientside use.
        ///     Send the ViewModel along with the ViewBag saved token and plan number.
        /// </remarks>
        /// <param name="id">The id number of the subscription plan to be started</param>
        /// <returns>The view which includes a checkout form to start an agreement, and the agreement details</returns>
        [HttpGet]
        public ActionResult CreateSubscription(int id)
        {
            //check for customer, if exists, generate a token off them
            //if not, generate a generic token and create the customer on post
            CreateCustomerViewModel model = new CreateCustomerViewModel {PlanId = id};

            using (_db)
            {
                model.User = _db.Users.Single(u => u.Email == User.Identity.Name);
            }

            //Token generation 
            var customerRequest = new CustomerSearchRequest().Email.Is(User.Identity.Name);
            ResourceCollection<Customer> collection = PaymentGateways.Gateway.Customer.Search(customerRequest);
            string clientToken;
            if (collection.Ids.Count != 0)
            {
                string custId = collection.FirstItem.Id;
                clientToken = PaymentGateways.Gateway.ClientToken.generate(
                    new ClientTokenRequest
                    {
                        CustomerId = custId
                    }
                );
            }
            else
            {
                clientToken = PaymentGateways.Gateway.ClientToken.generate();
            }
            ViewBag.ClientToken = clientToken;
            ViewBag.PlanID = model.PlanId;

            return View(model);
        }

        /// <summary>
        ///     Takes in data from the checkout form on the view, and processes a new subscription.
        /// </summary>
        /// <remarks>
        ///     Pull in the payment nonce and planID from the checkout form.
        ///     Get the user's details from the database.
        ///     Search for a customer record in the Braintree vault database.
        ///     If no matches exist,
        ///         Create a new customer using the pulled in payment nonce and user details.
        ///         Create a cardToken paymentmethod using the card details associated with the nonce.
        ///     In any case, check there is a cardToken available.
        ///     If there is no token, then there already was a Vaulted customer , so create the subscription request using the nonce itself).
        ///     Otherwise, use the newly generated cardToken from the new customer to create the subscription request.
        ///     In either case, submit a create request and receive a result object.
        ///     If the submission was successful, set the member level attribute of the user to the appropriate level.
        ///     If not successful, refresh the checkout page with a negative notification.         
        /// </remarks>
        /// <param name="collection">The data values gained from the form entries on the View page</param>
        /// <returns>
        ///     Refresh of the current page if the subscription request fails.
        ///     The Subscription Index page if the subscription request is successful.
        /// </returns>
        [HttpPost]
        public ActionResult CreateSubscription(FormCollection collection)
        {
            using (_db)
            {
                string nonceFromTheClient = collection["payment_method_nonce"];
                string planid = collection["planid"];
                string cardToken = "";
                var user = _db.Users.Single(u => u.Email == User.Identity.Name);
                
                //Search for customer
                var customerRequest = new CustomerSearchRequest().Email.Is(User.Identity.Name);
                ResourceCollection<Customer> results = PaymentGateways.Gateway.Customer.Search(customerRequest);
                if (results.Ids.Count == 0)
                {
                    //  If no result, create the customer, create cardToken
                    var request = new CustomerRequest
                    {
                        FirstName = user.FirstName,
                        LastName = user.LastName,
                        Email = User.Identity.Name,
                        Phone = "",
                        CreditCard = new CreditCardRequest
                        {
                            PaymentMethodNonce = nonceFromTheClient,
                            Options = new CreditCardOptionsRequest
                            {
                                VerifyCard = true
                            }
                        }
                    };

                    Result<Customer> result = PaymentGateways.Gateway.Customer.Create(request);
                    if (!result.IsSuccess())
                    {
                        TempData["message"] = result.Message;
                        return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
                    }
                    
                    cardToken = result.Target.PaymentMethods[0].Token;
                }

                SubscriptionRequest newSub;
                if (!cardToken.Equals(""))
                {
                    newSub = new SubscriptionRequest
                    {
                        PaymentMethodToken = cardToken,
                        PlanId = planid,
                        NeverExpires = true,
                        Options = new SubscriptionOptionsRequest
                        {
                            StartImmediately = true
                        }
                    };
                }
                else
                {
                    newSub = new SubscriptionRequest
                    {
                        PaymentMethodNonce = nonceFromTheClient,
                        PlanId = planid,
                        NeverExpires = true,
                        Options = new SubscriptionOptionsRequest
                        {
                            StartImmediately = true
                        }
                    };
                }
                

SourceWrestlingSchool/Views/Subscription/CreateSubscription.cshtml
@model SourceWrestlingSchool.Models.CreateCustomerViewModel
@{
    ViewBag.Title = "CreateCustomer";
    Layout = "~/Views/Shared/_Layout.cshtml";    
}
<link href="~/Content/newSub.css" rel="stylesheet" />
<script src="https://js.braintreegateway.com/js/braintree-2.31.0.min.js"></script>

@if (TempData["message"] != null)
{
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-ban"></i> Sorry!</h4>
    Your membership request has been declined at the payment stage. Subscription not created.
    Reason for Failure : @TempData["message"].ToString()
</div>
}

<h2>New Membership Agreement</h2>

<div class="container">
    <div class="row">
        <div class="col-lg-5">
            <div class="panel panel-default">
                <div class="panel-heading">Confirm Your Details</div>
                <div class="panel-body" style="color:black">
                    <ul>
                        <li>@Html.DisplayNameFor(model => model.User.FirstName) : @Html.DisplayFor(model => model.User.FirstName)</li>
                        <li>@Html.DisplayNameFor(model => model.User.LastName) : @Html.DisplayFor(model => model.User.LastName)</li>
                        <li>@Html.DisplayNameFor(model => model.User.Email) : @Html.DisplayFor(model => model.User.Email)</li>
                        <li>@Html.DisplayNameFor(model => model.User.PhoneNumber) : @Html.DisplayFor(model => model.User.PhoneNumber)</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-5">
            <div class="panel panel-default bootstrap-basic">
                <div class="panel-heading">
                    <h3 class="panel-title">Enter Card Details</h3>
                </div>
                <div class="panel-body">
                    <form id="checkout" method="post" action="/Subscription/CreateSubscription">
                        <div id="payment-form"></div>
                        <input class="btn btn-success" type="submit" value="Create Plan">
                        <input type="hidden" name="planid" value="@Html.Raw(ViewBag.PlanID)" />
                    </form>
                    <script>
                    
                        var clientToken = "@Html.Raw(ViewBag.ClientToken)";

                        braintree.setup(clientToken, "dropin", {
                                        container: "payment-form"
                                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

SourceWrestlingSchool/Views/Subscription/Index.cshtml
@model SourceWrestlingSchool.Models.SubscriptionViewModel

@{
    ViewBag.Title = "Subscriptions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/MemberPlans.css" rel="stylesheet" />

@if (TempData["message"] != null)
{
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-ban"></i> Congratulations!</h4>
        Your membership request has been accepted and a new subscription has been created.<br/>
        The details of the agreement are listed below.
    </div>
}

@if (Model.IsSubscribed)
{
    <div class="container">
        <h4>SubscriptionViewModel</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.IsSubscribed)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsSubscribed)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SubscriptionId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SubscriptionId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastPaymentDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastPaymentDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NextDueDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NextDueDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Username)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Username)
            </dd>

        </dl>
    </div>
}
else
{
    <div class="container">
        <section class="section">
            <div class="section-headlines text-center">
                <h2>Set up Membership Plan</h2>
                <p>Select which plan best suits your needs.</p>
            </div>
        
            <div class="row">
                <div class="pricing-table row-fluid text-center">
                    <div class="span4">
                        <div class="plan">
                            <div class="plan-name">
                                <h2>Bronze</h2>
                                <p class="muted">Basic membership</p>
                            </div>
                            <div class="plan-price">
                                <b>£40</b> / month
                            </div>
                            <div class="plan-details">
                                <div>
                                    <b>Unlimited</b> Group Classes
                                </div>                            
                                <div>
                                    <b>Supplementary</b> Special Seminars
                                </div>
                                <div>
                                    <b>Supplementary</b> Private Classes
                                </div>
                                <div>
                                    <b>25% off</b> Live Event Tickets
                                </div>
                            </div>
                            <div class="plan-action">
                                <a href="@Url.Action("CreateSubscription", "Subscription", new { id = 1 })" class="btn btn-block btn-large">
                                    <span>Choose Plan</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="plan prefered">
                            <div class="plan-name">
                                <h2>Silver</h2>
                                <p class="muted">Intermediate Membership</p>
                            </div>
                            <div class="plan-price">
                                <b>£55</b> / month
                            </div>
                            <div class="plan-details">
                                <div>
                                    <b>Unlimited</b> Group Classes
                                </div>
                                <div>
                                    <b>Free</b> Private Class / month
                                </div>
                                <div>
                                    <b>20% off</b> Special Seminars
                                </div>
                                <div>
                                    <b>25% off</b> Live Event Tickets
                                </div>
                            </div>
                            <div class="plan-action">
                                <a href="@Url.Action("CreateSubscription", "Subscription", new { id = 2 })" class="btn btn-block btn-large">
                                    <span>Choose Plan</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="plan">
                            <div class="plan-name">
                                <h2>Gold</h2>
                                <p class="muted">Full-featured Membership</p>
                            </div>
                            <div class="plan-price">
                                <b>£70</b> / month
                            </div>
                            <div class="plan-details">
                                <div>
                                    <b>Unlimited</b> Group Classes
                                </div>
                                <div>
                                    <b>Free</b> Private Class / month
                                </div>
                                <div>
                                    <b>Access</b> To Gym Facilities
                                </div>
                                <div>
                                    <b>25% off</b> Private Classes
                                </div>
                                <div>
                                    <b>25% off</b> Special Seminars
                                </div>
                                <div>
                                    <b>25% off</b> Live Event Tickets
                                </div>
                            </div>
                            <div class="plan-action">
                                <a href="@Url.Action("CreateSubscription", "Subscription", new { id = 3 })" class="btn btn-block btn-large">
                                    <span>Choose Plan</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>  
}